### ISSUE TITLE
I want to convert data into numerical values with Flytracker.

### ISSUE THREAD

**Issue by syokuhinmeneki** [kristinbranson/FlyTracker#1]
Hello.
I would like to convert the data in the graph that appears below the Vizia Riser into numerical data, but that is not working, so I would appreciate any guidance you can give me.

[2022.11.14 matlab flytracker.pptx](https://github.com/kristinbranson/FlyTracker/files/10008144/2022.11.14.matlab.flytracker.pptx)

I have attached a PowerPoint presentation of the graphs I would like to convert into numerical data.
Please refer to it.

**Comment by adamltaylor** [comment]
Ummm, hopefully you figured this out on your own.  If not, feel free to email me.
