### ISSUE TITLE
windows platform: rm -rf and cp command

### ISSUE THREAD

**Issue by LynnLvC** [kristinbranson/FlyTracker#2]
Hi, there are several places using the bash command 'rm -rf' and 'cp' commands, which of course does not work on Windows. So I would propose using the Matlab command _rmdir(**,'s')_, or _delete(*)_, and _copy_ to replace them.

**Comment by adamltaylor** [comment]
Fixed by a7a5d027ba49d91499be9127ecf3b3f63f625de9.
